AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'

DefaultScope:
  Exclude:
    - lib/r509/trollop.rb

StringLiterals:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

PredicateName: # is_ prefix
  Enabled: false

BlockNesting:
  Max: 4

# Offense count: 7
# Configuration parameters: EnforcedStyle, SupportedStyles.
ClassAndModuleChildren:
  Enabled: false

Void:
  Enabled: false

WordArray:
  Enabled: false

SignalException:
  Enabled: false

CaseIndentation:
  Enabled: false

NumericLiterals:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RedundantBegin:
  Enabled: false

RegexpLiteral:
  MaxSlashes: 2

HandleExceptions:
  Enabled: false

# False positive
LiteralInInterpolation:
  Enabled: false

# False positive
FileName:
  Enabled: false


# Future work

# Offense count: 8
# Configuration parameters: CountComments.
ClassLength:
  Max: 248

# Offense count: 26
CyclomaticComplexity:
  Max: 17

# Offense count: 1085
LineLength:
  Max: 564

# Offense count: 67
# Configuration parameters: CountComments.
MethodLength:
  Max: 42

# Offense count: 71
# Cop supports --auto-correct.
RedundantSelf:
  Enabled: false

UnusedMethodArgument:
  Enabled: false
