bundler_args: --without documentation
language: ruby
rvm:
 - 2.0.0
 - 2.3.1
 - ruby-head
 - rbx
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  irc:
    channels:
      - "irc.freenode.org#r509"
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
