bundler_args: --without documentation
language: ruby
rvm:
 - 1.9.3
 - 2.0.0
 - ruby-head
 - rbx-19mode
matrix:
  include:
  # This tests the X509Name UNDEF fix in R509::Subject. My patch to remove the need for this code landed in 1.9.3-p125
  # so we'll just ask for 1.9.3, install the OpenSSL PPAs I built to test non-EC, then compile 1.9.3-p0
  - rvm: 1.9.3
    env: R509_EC_SUPPORT_DISABLED=true
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
      env: R509_EC_SUPPORT_DISABLED=true
before_install:
  - ./.travis-scripts/ec-patch
  - if [ -n "$R509_EC_SUPPORT_DISABLED" ]; then rvm use ruby-1.9.3-p0; fi
  - if [ -n "$R509_EC_SUPPORT_DISABLED" ]; then gem install bundler --no-ri --no-rdoc; fi
