bundler_args: --without documentation
language: ruby
rvm:
 - 1.9.3
 - 2.0.0
 - ruby-head
 - rbx-19mode
before_install: gem install bundler #this is needed since ruby-head is broken on travis-ci right now
